# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: audible 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "audible"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Biddington"]
  s.date = "2014-07-08"
  s.description = "Object communications"
  s.email = "ben.biddington@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "audible.gemspec",
    "lib/audible.rb",
    "lib/audible/audible.rb",
    "lib/audible/pidfile.rb",
    "spec/spec_helper.rb",
    "spec/system.tests/drb/bin/server",
    "spec/system.tests/drb/drb_observers_spec.rb",
    "spec/system.tests/drb/support/drb_server.rb",
    "spec/unit.tests/and_how_it_differs_from_observable_spec.rb",
    "spec/unit.tests/examples/a_notifying_shell_spec.rb",
    "spec/unit.tests/examples/logging_as_notifications_spec.rb",
    "spec/unit.tests/it_notifies_despite_errors_spec.rb",
    "spec/unit.tests/listening_spec.rb",
    "spec/unit.tests/relaying_notifications/about_the_notifications_spec.rb",
    "spec/unit.tests/relaying_notifications/can_relay_notifications_spec.rb"
  ]
  s.homepage = "http://github.com/ben-biddington/audible"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Object communications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

